function [tree] = sci_loadTinyImages(tree)
// Copyright INRIA (Generated by M2SCI)
// Conversion function for Matlab loadTinyImages()
// Input: tree = Matlab funcall tree
// Output: tree = Scilab equivalent for tree
tree.lhs(1).dims=list(32,32,3,1)
tree.lhs(1).type=Type(Double,Real)
endfunction
